name: Build Pipeline

on:
  pull_request:
    branches: 
      - main
      - a[0-9]                   # CI on a1-a9 assignment branches

jobs:
  build:
    runs-on: ubuntu-latest     

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 21.6.1
        uses: actions/setup-node@v4
        with:
          node-version: 21.6.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build source code
        run: npm run build
